package server

var dashboardHTML = []byte(`<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Stockyard Relay</title><style>:root{--bg:#1a1410;--surface:#241c15;--border:#3d2e1e;--rust:#c4622d;--leather:#8b5e3c;--cream:#f5e6c8;--muted:#7a6550;--text:#e8d5b0}*{box-sizing:border-box;margin:0;padding:0}body{background:var(--bg);color:var(--text);font-family:'JetBrains Mono',monospace,sans-serif;min-height:100vh}header{background:var(--surface);border-bottom:1px solid var(--border);padding:1rem 2rem;display:flex;align-items:center;gap:1rem}.logo{color:var(--rust);font-size:1.25rem;font-weight:700}.badge{background:var(--rust);color:var(--cream);font-size:0.65rem;padding:0.2rem 0.5rem;border-radius:3px;font-weight:600;text-transform:uppercase}main{max-width:1100px;margin:0 auto;padding:2rem}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:1rem;margin-bottom:2rem}.stat{background:var(--surface);border:1px solid var(--border);border-radius:6px;padding:1.25rem;text-align:center}.stat-value{font-size:1.75rem;font-weight:700;color:var(--rust)}.stat-label{font-size:0.75rem;color:var(--muted);margin-top:0.25rem;text-transform:uppercase;letter-spacing:0.05em}.grid{display:grid;grid-template-columns:1fr 1fr;gap:1rem}.card{background:var(--surface);border:1px solid var(--border);border-radius:6px;padding:1.5rem}.card h2{font-size:0.85rem;color:var(--muted);text-transform:uppercase;letter-spacing:0.08em;margin-bottom:1rem}.form-row{display:flex;gap:0.5rem;margin-bottom:0.75rem;flex-wrap:wrap;align-items:flex-start}select,input,textarea{background:var(--bg);border:1px solid var(--border);color:var(--text);padding:0.5rem 0.75rem;border-radius:4px;font-family:inherit;font-size:0.85rem}.form-row select,.form-row input{flex:1}textarea{width:100%;min-height:80px;resize:vertical}.btn{background:var(--rust);color:var(--cream);border:none;padding:0.5rem 1rem;border-radius:4px;cursor:pointer;font-family:inherit;font-size:0.85rem;font-weight:600}.btn:hover{opacity:0.85}.btn-sm{padding:0.25rem 0.6rem;font-size:0.75rem}.btn-danger{background:#7a2020}table{width:100%;border-collapse:collapse;font-size:0.82rem}th{text-align:left;color:var(--muted);padding:0.5rem;border-bottom:1px solid var(--border);font-size:0.75rem;text-transform:uppercase}td{padding:0.5rem;border-bottom:1px solid var(--border)}.empty{color:var(--muted);font-size:0.85rem;padding:1rem 0;text-align:center}.full{grid-column:1/-1}.badge-g{background:#1a3a1a;color:#5cb85c;border:1px solid #2d5a2d;border-radius:3px;padding:0.1rem 0.4rem;font-size:0.72rem}.badge-r{background:#3a1a1a;color:#d9534f;border:1px solid #5a2d2d;border-radius:3px;padding:0.1rem 0.4rem;font-size:0.72rem}.badge-y{background:#3a2f1a;color:#f0ad4e;border:1px solid #5a4a2d;border-radius:3px;padding:0.1rem 0.4rem;font-size:0.72rem}</style></head>
<body><header><span class="logo">&#x2B21; Stockyard</span><span style="color:var(--muted)">/</span><span style="color:var(--cream);font-weight:600">Relay</span><span class="badge">Webhook Sender</span></header>
<main><div class="stats"><div class="stat"><div class="stat-value" id="s1">0</div><div class="stat-label">Events</div></div><div class="stat"><div class="stat-value" id="s2">0</div><div class="stat-label">Deliveries</div></div><div class="stat"><div class="stat-value" id="s3">FREE</div><div class="stat-label">Tier</div></div></div><div class="grid">
<div class="card"><h2>New Event Type</h2>
<div class="form-row"><input id="f-ename" placeholder="user.created"></div>
<div class="form-row"><input id="f-edesc" placeholder="Description"></div>
<button class="btn" onclick="createEvent()">Create Event</button>
<div style="margin-top:1rem;border-top:1px solid var(--border);padding-top:1rem">
<h2>Fire Event</h2>
<div class="form-row"><input id="f-fname" placeholder="event.name"></div>
<textarea id="f-fpayload">{"key":"value"}</textarea>
<button class="btn" style="margin-top:0.5rem" onclick="fireEvent()">Fire</button></div></div>
<div class="card"><h2>Subscribe</h2>
<div class="form-row"><input id="f-surl" placeholder="https://your-app.com/webhooks"></div>
<div class="form-row"><input id="f-seid" type="number" placeholder="Event ID"></div>
<div class="form-row"><input id="f-ssecret" placeholder="Signing secret (auto if blank)"></div>
<button class="btn" onclick="createSub()">Subscribe</button></div>
<div class="card full"><h2>Events</h2>
<table><thead><tr><th>Name</th><th>Description</th><th></th></tr></thead>
<tbody id="events-body"><tr><td colspan="3" class="empty">No events</td></tr></tbody></table></div>
<div class="card full"><h2>Subscriptions</h2>
<table><thead><tr><th>Event</th><th>Callback URL</th><th></th></tr></thead>
<tbody id="subs-body"><tr><td colspan="3" class="empty">No subscriptions</td></tr></tbody></table></div>
<div class="card full"><h2>Delivery Log</h2>
<table><thead><tr><th>Status</th><th>Payload</th><th>HTTP</th><th>Attempts</th><th>Time</th></tr></thead>
<tbody id="del-body"><tr><td colspan="5" class="empty">No deliveries</td></tr></tbody></table></div>
</div></main>
<script>
async function api(m,p,bd){var o={method:m,headers:{"Content-Type":"application/json"}};if(bd)o.body=JSON.stringify(bd);var r=await fetch(p,o);try{return await r.json();}catch(e){return {};}}  
async function load(){var s=await api("GET","/api/stats");var l=await api("GET","/api/limits");document.getElementById("s1").textContent=s.events||0;document.getElementById("s2").textContent=s.deliveries||0;document.getElementById("s3").textContent=(l.tier||"free").toUpperCase();loadEvents();loadSubs();loadDel();}
async function loadEvents(){var data=await api("GET","/api/events");var tbody=document.getElementById("events-body");if(!data||!data.length){tbody.innerHTML="<tr><td colspan='3' class='empty'>No events</td></tr>";return;}tbody.innerHTML=data.map(function(e){return "<tr><td style='color:var(--cream);font-family:monospace'>"+e.name+"</td><td style='color:var(--muted);font-size:0.82rem'>"+e.description+"</td><td><button class='btn btn-sm btn-danger' onclick='deleteEvent("+e.id+")'>Del</button></td></tr>";}).join("");}
async function loadSubs(){var data=await api("GET","/api/subscriptions");var tbody=document.getElementById("subs-body");if(!data||!data.length){tbody.innerHTML="<tr><td colspan='3' class='empty'>No subscriptions</td></tr>";return;}tbody.innerHTML=data.map(function(s){return "<tr><td style='font-family:monospace;font-size:0.8rem'>"+s.event_name+"</td><td style='font-size:0.8rem;color:var(--leather)'>"+s.callback_url+"</td><td><button class='btn btn-sm btn-danger' onclick='deleteSub("+s.id+")'>Del</button></td></tr>";}).join("");}
async function loadDel(){var data=await api("GET","/api/deliveries?limit=20");var tbody=document.getElementById("del-body");if(!data||!data.length){tbody.innerHTML="<tr><td colspan='5' class='empty'>No deliveries</td></tr>";return;}tbody.innerHTML=data.map(function(d){return "<tr><td><span class='badge-"+(d.status==="delivered"?"g":d.status==="failed"?"r":"y")+"'>"+d.status+"</span></td><td style='font-size:0.75rem;color:var(--muted);max-width:200px;overflow:hidden;text-overflow:ellipsis'>"+String(d.payload||"").substring(0,60)+"</td><td>"+d.response_code+"</td><td>"+d.attempts+"</td><td style='font-size:0.75rem;color:var(--muted)'>"+new Date(d.created_at).toLocaleTimeString()+"</td></tr>";}).join("");}
async function createEvent(){var e={name:document.getElementById("f-ename").value.trim(),description:document.getElementById("f-edesc").value.trim()};if(!e.name){alert("Name required");return;}var res=await api("POST","/api/events",e);if(res.error){alert(res.error);return;}document.getElementById("f-ename").value="";load();}
async function fireEvent(){var name=document.getElementById("f-fname").value.trim();if(!name){alert("Event name required");return;}var raw=document.getElementById("f-fpayload").value.trim();var body;try{body=JSON.parse(raw);}catch(e){alert("Invalid JSON");return;}var res=await api("POST","/api/fire/"+name,body);if(res.error){alert(res.error);return;}alert("Fired. Deliveries queued: "+res.deliveries_queued);setTimeout(load,500);}
async function createSub(){var s={event_id:parseInt(document.getElementById("f-seid").value)||0,callback_url:document.getElementById("f-surl").value.trim(),secret:document.getElementById("f-ssecret").value.trim()};if(!s.callback_url){alert("URL required");return;}var res=await api("POST","/api/subscriptions",s);if(res.error){alert(res.error);return;}if(res.secret){alert("Created. Signing secret: "+res.secret);}document.getElementById("f-surl").value="";load();}
async function deleteEvent(id){if(!confirm("Delete?"))return;await api("DELETE","/api/events/"+id);load();}
async function deleteSub(id){if(!confirm("Delete?"))return;await api("DELETE","/api/subscriptions/"+id);load();}
load();setInterval(loadDel,3000);
</script></body></html>`)
