package server
import "net/http"
func(s *Server)dashboard(w http.ResponseWriter,r *http.Request){w.Header().Set("Content-Type","text/html; charset=utf-8");w.Write([]byte(dashHTML))}
const dashHTML=`<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Relay</title>
<style>:root{--bg:#1a1410;--bg2:#241e18;--bg3:#2e261e;--rust:#c45d2c;--rl:#e8753a;--leather:#a0845c;--cream:#f0e6d3;--cd:#bfb5a3;--cm:#7a7060;--gold:#d4a843;--green:#4a9e5c;--mono:'JetBrains Mono',Consolas,monospace;--serif:'Libre Baskerville',Georgia,serif}*{margin:0;padding:0;box-sizing:border-box}body{background:var(--bg);color:var(--cream);font-family:var(--mono);font-size:13px;line-height:1.6}.hdr{padding:.6rem 1.2rem;border-bottom:1px solid var(--bg3);display:flex;justify-content:space-between;align-items:center}.hdr h1{font-family:var(--serif);font-size:1rem}.hdr h1 span{color:var(--rl)}.main{max-width:800px;margin:0 auto;padding:1rem}.btn{font-family:var(--mono);font-size:.68rem;padding:.3rem .6rem;border:1px solid;cursor:pointer;background:transparent}.btn-p{border-color:var(--rust);color:var(--rl)}.btn-p:hover{background:var(--rust);color:var(--cream)}.card{background:var(--bg2);border:1px solid var(--bg3);padding:.6rem;margin-bottom:.4rem;cursor:pointer;transition:.1s}.card:hover{background:var(--bg3)}.card h3{font-size:.8rem;margin-bottom:.15rem}.card-meta{font-size:.65rem;color:var(--cm);display:flex;gap:.7rem}.del-row{padding:.3rem .5rem;border-bottom:1px solid var(--bg3);font-size:.72rem;display:flex;gap:.5rem}.empty{text-align:center;padding:2rem;color:var(--cm);font-style:italic;font-family:var(--serif)}.modal-bg{position:fixed;top:0;left:0;right:0;bottom:0;background:rgba(0,0,0,.65);display:flex;align-items:center;justify-content:center;z-index:100}.modal{background:var(--bg2);border:1px solid var(--bg3);padding:1.5rem;width:90%;max-width:500px;max-height:90vh;overflow-y:auto}.modal h2{font-family:var(--serif);font-size:.9rem;margin-bottom:1rem}label.fl{display:block;font-size:.65rem;color:var(--leather);text-transform:uppercase;letter-spacing:1px;margin-bottom:.2rem;margin-top:.5rem}input[type=text]{background:var(--bg);border:1px solid var(--bg3);color:var(--cream);padding:.35rem .5rem;font-family:var(--mono);font-size:.78rem;width:100%;outline:none}</style>
<link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville:ital@0;1&family=JetBrains+Mono:wght@400;600&display=swap" rel="stylesheet">
</head><body><div class="hdr"><h1><span>Relay</span></h1><button class="btn btn-p" onclick="showNew()">+ Channel</button></div>
<div class="main"><div id="upgrade-banner" style="display:none;background:#241e18;border:1px solid #8b3d1a;border-left:3px solid #c45d2c;padding:.6rem 1rem;font-size:.78rem;color:#bfb5a3;margin-bottom:.8rem"><strong style="color:#f0e6d3">Free tier</strong> — 10 items max. <a href="https://stockyard.dev/relay/" target="_blank" style="color:#e8753a">Upgrade to Pro →</a></div><div id="list"></div><div id="detail" style="display:none;margin-top:1rem"></div></div><div id="modal"></div>
<script>
async function api(u,o){return(await fetch(u,o)).json()}
function esc(s){return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
function timeAgo(d){if(!d)return'never';const s=Math.floor((Date.now()-new Date(d))/1e3);if(s<60)return s+'s ago';if(s<3600)return Math.floor(s/60)+'m ago';return Math.floor(s/3600)+'h ago'}
async function load(){const d=await api('/api/channels');const chs=d.channels||[];
document.getElementById('list').innerHTML=chs.length?chs.map(c=>'<div class="card" onclick="open_(\''+c.id+'\')"><h3>'+esc(c.name)+' <span style="color:var(--cm);font-size:.65rem">/hook/'+esc(c.slug)+'</span></h3><div class="card-meta"><span>'+c.delivery_count+' webhooks</span><span>last: '+timeAgo(c.last_webhook)+'</span></div></div>').join(''):'<div class="empty">No channels yet. Create one to start receiving webhooks.</div>'}
async function open_(id){const[c,dd]=await Promise.all([api('/api/channels/'+id),api('/api/channels/'+id+'/deliveries')]);
const dels=(dd.deliveries||[]).map(d=>'<div class="del-row"><span style="color:var(--green);font-weight:600;width:40px">'+d.method+'</span><span style="flex:1;color:var(--cd);font-size:.68rem;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">'+esc(d.body.substring(0,100))+'</span><span style="color:var(--cm);font-size:.6rem">'+d.source_ip+'</span><span style="color:var(--cm);font-size:.6rem">'+timeAgo(d.created_at)+'</span></div>').join('');
document.getElementById('detail').style.display='block';
document.getElementById('detail').innerHTML='<div style="display:flex;justify-content:space-between;margin-bottom:.5rem"><div><span style="font-size:.75rem;color:var(--leather)">'+esc(c.name)+'</span><div style="font-size:.65rem;color:var(--cm)">Endpoint: <span style="color:var(--rl)">'+location.origin+'/hook/'+esc(c.slug)+'</span></div></div><button class="btn" style="border-color:var(--bg3);color:var(--cm)" onclick="if(confirm(\'Delete?\'))delCh(\''+id+'\')">Del</button></div>'+(dels||'<div class="empty" style="padding:1rem">No webhooks received yet.</div>')}
async function delCh(id){await api('/api/channels/'+id,{method:'DELETE'});document.getElementById('detail').style.display='none';load()}
function showNew(){document.getElementById('modal').innerHTML='<div class="modal-bg" onclick="if(event.target===this)closeModal()"><div class="modal"><h2>New Channel</h2><label class="fl">Name</label><input type="text" id="nc-name" placeholder="GitHub Webhooks"><label class="fl">Slug (URL path)</label><input type="text" id="nc-slug" placeholder="github"><label class="fl">Forward Targets (comma-separated URLs)</label><input type="text" id="nc-targets" placeholder="https://my-app.com/webhook"><div style="display:flex;gap:.5rem;margin-top:1rem"><button class="btn btn-p" onclick="save()">Create</button><button class="btn" style="border-color:var(--bg3);color:var(--cm)" onclick="closeModal()">Cancel</button></div></div></div>'}
async function save(){const b={name:document.getElementById('nc-name').value,slug:document.getElementById('nc-slug').value,targets:document.getElementById('nc-targets').value};if(!b.name||!b.slug){alert('Name and slug required');return};await api('/api/channels',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});closeModal();load()}
function closeModal(){document.getElementById('modal').innerHTML=''}
load();setInterval(()=>{load()},10000)
fetch('/api/tier').then(r=>r.json()).then(j=>{if(j.tier==='free'){var b=document.getElementById('upgrade-banner');if(b)b.style.display='block'}}).catch(()=>{var b=document.getElementById('upgrade-banner');if(b)b.style.display='block'});
</script></body></html>`
